Repository sparkdotfi/spark-address-registry, pull requests merged in 2024-04, with the labels that each got.

#1 feat: Add addresses first pass (SC-365)
  .github/workflows/ci.yml
  src/Counter.sol
  src/Ethereum.sol
  src/Gnosis.sol
  test/Counter.t.sol
Labels: Priority: High, Status: Revisions Needed

#2 Add MCD chief
  src/Ethereum.sol
Labels: Priority: High, Status: Ready for Review

#3 feat: Add libraries
  src/Ethereum.sol
Labels: Priority: Medium, Status: Ready for Review

#4 feat: Add DSR oracle related addresses
  src/Base.sol
  src/Ethereum.sol
  src/Optimism.sol
Labels: Priority: High, Status: Ready for Review

#5 [SC-388] Add new addresses from the April 17 spell as well as rewards multisig
  .github/workflows/ci.yml
  src/Ethereum.sol
  src/Gnosis.sol
Labels: Priority: High, Status: Ready for Review
