Repository sparkdotfi/spark-address-registry, pull requests merged in 2024-06, with the labels that each got.

#7 Add psm variant1 user actions
  src/Ethereum.sol
Labels: Priority: High, Status: Ready for Review

#8 feat: add WEETH addresses
  src/Ethereum.sol
Labels: Priority: Medium, Status: Ready for Review

#9 feat: add DSR_FORWARDER_ARBITRUM
  src/Arbitrum.sol
  src/Ethereum.sol
Labels: Priority: Low, Status: Ready for Review

#10 chore: remove bridging addresses
  src/Base.sol
  src/Gnosis.sol
  src/Optimism.sol
Labels: Priority: Low, Status: Ready for Review

#11 refactor: update pragmas
  src/Arbitrum.sol
  src/Base.sol
  src/Ethereum.sol
  src/Gnosis.sol
  src/Optimism.sol
Labels: Priority: Medium, Status: Ready for Review

#13 docs: update readme
  README.md
Labels: Priority: Medium, Status: Ready for Review

#14 feat: add back AMB_EXECUTOR
  src/Gnosis.sol
Labels: Priority: Medium, Status: Ready for Review
